### ISSUE TITLE
Feature request: Add support to configure plugin without service worker

### ISSUE THREAD

**Issue by Edmund1645** [rishabh3112/gridsome-plugin-pwa#13]
I noticed that after not including the `serviceWorkerPath` in the plugin configuration, a service worker file is still generated in the root directory.

It would be nice to have an option where one can choose to use a service worker or not.

**Comment by rishabh3112** [comment]
Hi @Edmund1645 .
If you need starting point for the PR:
We just need to gracefully handle `createServiceWorker` function if there is no `serviceWorkerPath` provided in `service-worker.js` file
You may ask for help if you get stuck.

**Comment by Edmund1645** [comment]
Sure @rishabh3112 , I'll like to work on it.

**Comment by rishabh3112** [comment]
@Edmund1645 ping

**Comment by rishabh3112** [comment]
@Edmund1645 let me know the status and whether you need any help.

**Comment by Edmund1645** [comment]
I have been busy on another project, I'll provide feedback soon please.

**Comment by cbaone** [comment]
+1 for this. 

In the meantime, what's the best way to unregister the service worker? It is killing the benefits of Netlify ever since we disabled the plugin. I can't seem to find a clear and simple way to do it in the gridsome.config.js

**Comment by rishabh3112** [comment]
@cbaone The exact functionality is not possible as of now through this plugin. I am using [`generateSW`](https://developers.google.com/web/tools/workbox/modules/workbox-build) for generating service worker (which seems to be good enough for most cases). Higher customization may be done using `injectManifest`.

I am looking to implement it, but it may take time ( because I am busy due to university ). Meanwhile, you can open a pull request for this and I am happy to guide you through it :)

**Comment by rishabh3112** [comment]
I have pushed a new `disableServiceWorker` option for this as of now. Feel free to open the issue if required :)
